# Generated by Django 5.1.1 on 2024-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
